AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for backend

Globals:
  Function:
    Timeout: 29

Parameters:
  Env:
    Type: String
    Default: prod

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Api-Key'"
        AllowOrigin: "'*'" # make this more strict
  ApiUsagePlan:
    Type: "AWS::ApiGateway::UsagePlan"
    Properties:
      ApiStages:
        - ApiId: !Ref Api
          Stage: dev
      Description: !Sub ${AWS::StackName} usage plan
      Quota:
        Limit: 1000
        Period: MONTH
      UsagePlanName: !Sub ${AWS::StackName}-usage-plan
  getEvents:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event-signup-backend-getEvents-dev
      CodeUri: src/
      Handler: handler.eventsGetAllHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /events
            Method: get
            Auth:
              ApiKeyRequired: true
      Environment:
        Variables:
          ENV: !Ref Env
      Policies:
        - Statement:
            - Sid: dynamoGetAllEventsPolicy
              Effect: Allow
              Action:
                - dynamodb:scan
                - dynamodb:Query
              Resource: "*"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handler.ts
  addEvent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event-signup-backend-postEvents-dev
      CodeUri: src/
      Handler: handler.eventsPostHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /events
            Method: post
            Auth:
              ApiKeyRequired: true
      Environment:
        Variables:
          ENV: !Ref Env
      Policies:
        - Statement:
            - Sid: dynamoPostEventsPolicy
              Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: "*"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handler.ts
