AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for backend

Globals:
  Function:
    Timeout: 3

Resources:
  getEvents:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.eventsGetHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /events
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handler.ts
  addEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.eventsPostHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /events
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handler.ts
